version: "3.7"
services:
  dashboard-server:
    build:
      context: .
    environment:
      TZ: Australia/Brisbane
      WEATHER_KEY:
      CRYPTO_KEY:
    ports:
      - "3000:3000"
    restart: unless-stopped
