version: "3.7"
services:
  app:
    build:
      context: .
    environment:
      WEATHER_KEY: ""
      CRYPTO_KEY: ""
      TZ: Australia/Brisbane
    ports:
      - "3000:3000"
    restart: always
